export const categories = [
  { id: "electronics", name: "Electronics" },
  { id: "clothing", name: "Clothing" },
  { id: "home", name: "Home & Kitchen" },
  { id: "beauty", name: "Beauty & Personal Care" },
  { id: "sports", name: "Sports & Outdoors" },
  { id: "toys", name: "Toys & Games" },
]

export const allProducts = [
  {
    id: 1,
    name: "Sony WH-1000XM5",
    price: 349.99,
    category: "electronics",
    image: "/diverse-music-lovers.png",
    description: "Industry-leading noise cancellation with exceptional sound quality",
    rating: 4.8,
    reviewCount: 1245,
    date: "2025-03-15",
  },
  {
    id: 2,
    name: "Bose QuietComfort Ultra",
    price: 379.99,
    category: "electronics",
    image: "/luxurious-listening.png",
    description: "Immersive audio with spatial audio technology",
    rating: 4.7,
    reviewCount: 982,
    date: "2025-02-20",
  },
  {
    id: 3,
    name: "Apple AirPods Max",
    price: 549.99,
    category: "electronics",
    image: "/sleek-silver-headphones.png",
    description: "Computational audio with H1 chip and adaptive EQ",
    rating: 4.6,
    reviewCount: 1876,
    date: "2025-01-10",
  },
  {
    id: 4,
    name: "Sennheiser Momentum 4",
    price: 299.99,
    category: "electronics",
    image: "/premium-audio-experience.png",
    description: "Superior sound with 60-hour battery life",
    rating: 4.5,
    reviewCount: 763,
    date: "2025-03-05",
  },
  {
    id: 5,
    name: "Apple Watch Series 9",
    price: 399.99,
    category: "electronics",
    image: "/modern-smartwatch-display.png",
    description: "Advanced health features and always-on Retina display",
    rating: 4.7,
    reviewCount: 2341,
    date: "2025-04-01",
  },
  {
    id: 6,
    name: "Samsung Galaxy Watch 6",
    price: 299.99,
    originalPrice: 349.99,
    category: "electronics",
    image: "/wrist-tech-lifestyle.png",
    description: "Track your health and fitness with advanced sensors",
    rating: 4.5,
    reviewCount: 1245,
    date: "2025-02-15",
  },
  {
    id: 7,
    name: "Garmin Venu 3",
    price: 449.99,
    category: "electronics",
    image: "/outdoor-adventure-smartwatch.png",
    description: "Premium GPS smartwatch with up to 14 days battery life",
    rating: 4.6,
    reviewCount: 876,
    date: "2025-03-20",
  },
  {
    id: 8,
    name: "Linen Beach Shirt",
    price: 29.99,
    originalPrice: 49.99,
    category: "clothing",
    image: "/relaxed-linen-shore.png",
    description: "Breathable linen shirt perfect for summer",
    rating: 4.3,
    reviewCount: 542,
    date: "2025-04-05",
  },
  {
    id: 9,
    name: "Cotton Shorts",
    price: 19.99,
    originalPrice: 34.99,
    category: "clothing",
    image: "/relaxed-summer-shorts.png",
    description: "Comfortable cotton shorts for hot days",
    rating: 4.2,
    reviewCount: 387,
    date: "2025-03-25",
  },
  {
    id: 10,
    name: "Summer Dress",
    price: 39.99,
    originalPrice: 69.99,
    category: "clothing",
    image: "/breezy-floral-dress.png",
    description: "Light and flowy summer dress",
    rating: 4.4,
    reviewCount: 621,
    date: "2025-04-10",
  },
  {
    id: 11,
    name: "Straw Hat",
    price: 15.99,
    originalPrice: 24.99,
    category: "clothing",
    image: "/placeholder.svg?height=200&width=200&query=straw%20hat",
    description: "Stylish sun protection for summer",
    rating: 4.1,
    reviewCount: 298,
    date: "2025-03-15",
  },
  {
    id: 12,
    name: "KitchenAid Stand Mixer",
    price: 349.99,
    category: "home",
    image: "/placeholder.svg?height=200&width=200&query=kitchenaid%20mixer",
    description: "Professional-grade stand mixer with 10 speeds",
    rating: 4.9,
    reviewCount: 3245,
    date: "2025-01-20",
  },
  {
    id: 13,
    name: "Vitamix Blender",
    price: 499.99,
    originalPrice: 549.99,
    category: "home",
    image: "/placeholder.svg?height=200&width=200&query=vitamix%20blender",
    description: "High-performance blender for smoothies and more",
    rating: 4.8,
    reviewCount: 2187,
    date: "2025-02-10",
  },
  {
    id: 14,
    name: "Dyson Air Purifier",
    price: 399.99,
    category: "home",
    image: "/placeholder.svg?height=200&width=200&query=dyson%20air%20purifier",
    description: "HEPA air purifier and fan with air quality monitoring",
    rating: 4.7,
    reviewCount: 1543,
    date: "2025-03-05",
  },
  {
    id: 15,
    name: "Nespresso Coffee Maker",
    price: 149.99,
    originalPrice: 199.99,
    category: "home",
    image: "/placeholder.svg?height=200&width=200&query=nespresso%20coffee%20maker",
    description: "Premium coffee maker for barista-quality espresso",
    rating: 4.6,
    reviewCount: 1876,
    date: "2025-02-25",
  },
  {
    id: 16,
    name: "ASUS ROG Zephyrus",
    price: 1799.99,
    category: "electronics",
    image: "/placeholder.svg?height=200&width=200&query=asus%20gaming%20laptop",
    description: "Ultra-slim gaming laptop with RTX 4070",
    rating: 4.7,
    reviewCount: 876,
    date: "2025-04-15",
  },
  {
    id: 17,
    name: "Alienware m16 R2",
    price: 2199.99,
    originalPrice: 2399.99,
    category: "electronics",
    image: "/placeholder.svg?height=200&width=200&query=alienware%20gaming%20laptop",
    description: "High-performance gaming with advanced cooling",
    rating: 4.8,
    reviewCount: 543,
    date: "2025-03-20",
  },
  {
    id: 18,
    name: "Lenovo Legion Pro 7",
    price: 1899.99,
    category: "electronics",
    image: "/placeholder.svg?height=200&width=200&query=lenovo%20legion%20laptop",
    description: "Powerful gaming laptop with 240Hz display",
    rating: 4.6,
    reviewCount: 421,
    date: "2025-02-28",
  },
  {
    id: 19,
    name: "Bluetooth Speaker",
    price: 79.99,
    category: "electronics",
    image: "/audio-system.png",
    description: "Portable waterproof bluetooth speaker",
    rating: 4.4,
    reviewCount: 987,
    date: "2025-03-10",
  },
  {
    id: 20,
    name: "Laptop Backpack",
    price: 59.99,
    originalPrice: 79.99,
    category: "clothing",
    image: "/colorful-travel-backpack.png",
    description: "Durable laptop backpack with USB charging port",
    rating: 4.5,
    reviewCount: 1243,
    date: "2025-04-05",
  },
  {
    id: 21,
    name: "Yoga Mat",
    price: 29.99,
    category: "sports",
    image: "/placeholder.svg?height=200&width=200&query=yoga%20mat",
    description: "Non-slip yoga mat with alignment markings",
    rating: 4.3,
    reviewCount: 876,
    date: "2025-03-15",
  },
  {
    id: 22,
    name: "Resistance Bands Set",
    price: 24.99,
    originalPrice: 34.99,
    category: "sports",
    image: "/placeholder.svg?height=200&width=200&query=resistance%20bands",
    description: "Complete set of resistance bands for home workouts",
    rating: 4.4,
    reviewCount: 654,
    date: "2025-02-20",
  },
  {
    id: 23,
    name: "Fitness Tracker",
    price: 89.99,
    category: "sports",
    image: "/placeholder.svg?height=200&width=200&query=fitness%20tracker",
    description: "Track your steps, heart rate, and sleep patterns",
    rating: 4.5,
    reviewCount: 1432,
    date: "2025-03-25",
  },
  {
    id: 24,
    name: "Moisturizing Face Cream",
    price: 24.99,
    category: "beauty",
    image: "/placeholder.svg?height=200&width=200&query=face%20cream",
    description: "Hydrating face cream with hyaluronic acid",
    rating: 4.6,
    reviewCount: 987,
    date: "2025-04-10",
  },
]
